version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-portfolio
    ports:
      - "8080:80"
    volumes:
      - ./assets:/usr/share/nginx/html/assets
    restart: unless-stopped 